version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pulsecart-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pulsecart
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pimage"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pulsecart-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pulsecart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - AZURE_STORAGE_CONNECTION_STRING=none
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend-uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pulsecart-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
  backend-uploads:
